pipeline {
    agent {
        label ("aws-deploy")
            }
    stages {

        stage('test auth') {
	     agent {
            docker {
              image 'golang:alpine'
            }
           }
            steps {
                sh '''
            cd weatherapp/auth/
            go build 
            cd -
            ls -la
                '''
            }
        }


        stage('Hello2') {
            steps {
                sh '''
                ls 
                pwd
                '''
            }
        }

        stage('Hello3') {
            steps {
                sh '''
                ls 
                pwd
                '''
            }
        }


    }






}